# Generated by Django 3.0.4 on 2020-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MailStatusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField(default=0)),
                ('mail_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='log_adapter.MailStatus')),
            ],
        ),
        migrations.CreateModel(
            name='MailStatusEventAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('confidence', models.IntegerField(default=0)),
                ('aggregate', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='log_adapter.MailStatusEvent')),
            ],
        ),
        migrations.CreateModel(
            name='MailStatusAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('confidence', models.IntegerField(default=0)),
                ('aggregate', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField(default=0)),
                ('mail_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='log_adapter.MailStatus')),
            ],
        ),
    ]
